= Lorem ipsum 2

1 - Réconciliez vous avec Spring
================================
Je travaille depuis plusieurs semaines avec Spring Boot. Je dois avouer que l'idée de mettre en place ce nouvel outil ne m'enchantait gère. Bien sûr j'avais eu de bons retours mais après plusieurs années, je m'étais lassé de l'écosystème Spring : trop lourd, trop de librairies, trop JEE ... Je continuais à utiliser Spring dans mes projets plus par habitude que par conviction.

Je dois admettre que Spring Boot est aujourd'hui une évidence pour moi ; c'est le projet qui a rendu à Spring sa simplicité d'origine (et sans XML s'il vous plait).

Prenons l'application REST suivante :

[source,java]
.Classe principale
----
@Configuration
@EnableAutoConfiguration
@ComponentScan
public class Application {
       
	public static void main(String[] args) {
        	SpringApplication.run(Application.class, args);
	}
     
}
----

[source,java]
.Services REST
----
@RestController
@RequestMapping("/api")
public class RestServices {
	@RequestMapping(method = RequestMethod.GET)
    public
    @ResponseBody
    String ping() {
    	return "{\"status\":\"OK\",\"timestamp\":\"" + System.currentTimeMillis() + "\"}";
    }
}
----

*Voilà, c'est tout !*

En effet, plus de configuration XML, plus de déclaration de beans à rallonge, plus de web.xml. Tout n'est pas nouveau bien sûr (configuration Java notamment) mais Spring Boot à pousser la logique de simplification entamée par Spring depuis plusieurs années à son maximum.

En effet, nous avons ici une application web complète qu'il est possible de lancer dans la foulée (oui sans serveur d'application...en apparence, nous y reviendrons) :

[source,bash]
----
...
2015-05-27 14:28:49.114&nbsp; INFO 50883 --- [ost-startStop-1] o.s.web.context.ContextLoader : Root WebApplicationContext: initialization completed in 2102 ms
----

avec le test correspondant :

[source,bash]
----
~$ curl http://localhost:8080/api
{"status":"OK","timestamp":"1432733392861"}
----
    
2 - KISS ("Keep It Simple, Stupid")
===================================
blabla