= JXLS - Reporting Excel
:hp-tags: JXLS, Reporting, CSV, OpenData

JXLS
==========

Quand on parle Excel dans le monde Java, on pense tout de suite à l'acteur historique Apache POI. POI permet depuis depuis de nombreuses années de manipuler les formats Microsoft Office au sein de l'écosystème Java. Le gros avantage de POI quand on veut manipuler le format XLS par exemple est son extrême richesse ; pour autant, cette richesse en terme d'API se fait au détriment la clarté du code : ceux qui ont déjà créé from scratch un fichier Excel via POI savent que le code nécessaire à la génération de ce dernier est extrêmement verbeux.

C'est là que JXLS vient à la rescousse. En effet, JXLS n'a pas pour objectif de founir une nouvelle API Java MS Office (au contraire même puisqu'il utilise POI en interne) mais de fournir un outil qui va simplifier la création de rapport Excel en partant de fichiers templates, en se concentrant uniquement sur les données et le remplissage du fichier à l'aide de plusieurs raccourcis syntaxiques extrêmement concis.

D'abord le jeu de données
=========================