= Introduction à Prometheus
:hp-tags: Prometheus, Monitoring, Spring Boot, Docker

Prometheus
==========

Prometheus est un des derniers nés dans le domaine du monitoring (développé chez SoundCloud majoritairement en Go) - il vient ainsi marcher sur les plate-bandes de solutions comme Graphite mais avec une approche globale.

En effet, au-delà du stockage de métriques, Promotheus fournit :

* une collecte active des métriques (ie. Prometheus collecte les données des systèmes monitorés via des endpoints fournis par ces derniers - Prometheus fournit également un système de push pour les systèmes ne pouvant pas fournir de point d'entrée)
* un système d'alerting (email, slack, webhook ...)
* un gestionnaire de dashboard dédié (PromDash)
* un modèle de données clé/valeur (système de labels permettant une identification fine des métriques)
* un système simple de requêtage des métriques

Pourquoi monitorer vos applications ?
=====================================

La réponse est multiple et sera forcément lié à votre environnement de production et votre environnement métier :

* Evolution de stocks
* Impact des actions marketing sur les demandes client
* Usage CPU, RAM
* Temps de réponse des requêtages DB
* Serveur Up/Down
* ...

Mise en oeuvre
==============

Au-delà de nombreuses fonctionnalités offertes par Prometheus, l'un des principaux avantages de ce dernier est sa rapidité et sa facilité de mise en oeuvre.

Pour vous démontrer cela, nous nous appuierons sur l'Open Data du réseau de vélo de Rennes Métropole. Nous allons monitorer l'ensemble des docks vélo de Rennes et visualiser  en temps réel les places et vélos disponibles pour chacun d'entre eux.

1 - Mise à disposition d'un Endpoint Prometheus

Le format de données des métriques Prometheus est simple mais pour autant très souple (système de clé/valeur appelé label). Il est ainsi possible de modéliser différentes dimensions d'une même métrique via un ou plusieurs labels.

Une métrique est modélisée par une ou plusieurs lignes ASCII contenant :
- le nom de la métrique
- les labels de la métrique
- la valeur de la métrique

Exemple : métrique fournissant le nombre de vélos disponibles à Rennes à l'heure actuelle

[source,json]
----
bikes_available{station="SAINTE THERESE"} 11
bikes_available{station="SAINTE-ANNE"} 12
----

Dans l'exemple précédent :

* bikes_available correspond au nom de la métrique
* station est un label fournissant le nom du dock vélo (il est bien sûr possible de fournir plusieurs labels)
* 11/12 correspondent aux nombres de vélos disponibles dans les 2 stations spécifiées ici

Aussi, afin de fournir en temps réel les données à Prometheus, il suffit de fournir une URL ayant pour contenu les données attendues dans ce format. Pour cela, nous utiliserons ici Spring Boot mais il est bien sûr possible d'utiliser votre langage favori.

Le code suivant fournit 2 métriques via https://data.keolis-rennes.com/[l'API OpenData] du réseau de vélos de Rennes fourni par Keolis :

- bikes_available - nombre de vélos disponibles à une station donnée (identifié par un label *station*)
- slots_available - nombre d'emplacements de vélo disponibles à une station donnée (identifié par un label *station*)

[source,java]
----
@RestController
@RequestMapping("/metrics")
public class MetricsResource {

    @RequestMapping(method = RequestMethod.GET, produces={"text/plain"})
    public ResponseEntity<String> get() {
        RestTemplate restTemplate = new RestTemplate();
        Response response = restTemplate.getForObject("http://data.keolis-rennes.com/json/?version=2.0&key=PYM7IXA0P1M728I&cmd=getbikestations", Response.class);

        StringBuilder metricsBuilder = new StringBuilder();
        for (Station station : response.getOpendata().getAnswer().getData().getStations()) {
            metricsBuilder.append("bikes_available{station=\"" + station.getName() + "\"} " + station.getBikesavailable() +"\n");
            metricsBuilder.append("slots_available{station=\"" + station.getName() + "\"} " + station.getSlotsavailable() +"\n");
        }

        return new ResponseEntity<>(metricsBuilder.toString(), HttpStatus.OK);
    }

}
----

2 - Configuration Prometheus

[source,yaml]
----
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  labels:
      monitor: 'rennes-bike-monitor'

rule_files:

scrape_configs:
  - job_name: 'rennes-bike'

    scrape_interval: 5s # intervalle de lecture de la source de données
    scrape_timeout: 10s

    target_groups:
      - targets: ['192.168.1.17:8080'] # adresse de la source de données
----

3 - Serveur Prometheus

4 - Dashboard PromDash
