Breizhcamp Saison 5
===================

La 5ème saison du http://www.breizhcamp.org/[Breizhcamp] a eu lieu du 10 au 12 juin dernier. Elle a réuni 2^8 (256 donc) personnes sur le campus de Beaulieu à Rennes. http://www.ellixo.com/[Ellixo] était bien évidemment présent.

On passera rapidement sur le mercredi après-midi car, c'est aussi ça le BreizhCamp, nous avons passons plus de temps à causer qu'à nous cultiver ! Pour autant, nous avons pu assister à une très bonne introduction à http://mesos.apache.org[Mesos] par Aurélien Maury, Pablo Lopez, Jean-Baptiste Claramonte et Jean-Pascal Thiery - sujet pas évident à présenter sur les problématiques de gestion de ressources système (CPU, RAM, ..) au sein d'un cluster (forcément hétérogène) mais amené de manière très claire et synthétique.

Pour le reste, l'équipe du Breizhcamp a encore fait fort cette année, les keynotes du jeudi en témoignent. Après une bonne première keynote de https://www.ovh.com/[OVH] (nouveau venu rennais) faisant le parallèle entre problématiques de production et le Mont St-Michel (démarche étonnante mais qui tenait la route - vous pourrez vérifier par vous-même : les vidéos des conférences seront disponibles en ligne dans les jours qui viennent), Christel Le Coq de http://www.b-sensory.com/[B.Sensory] est venu nous raconter son expérience de startupeuse. Au travers d'anecdotes croustillantes, elle a raconté son parcours, de l'idée à la réalisation du prototype Little Bird. Little Bird est le "Premier sextoy synchronisé à vos lectures érotiques". Elle a su conquérir un public majoritairement masculin ; premier pari gagné pour l'équipe du Breizhcamp : une des meilleures keynotes qu'il nous ait été donnée de voir depuis les débuts du BreizhCamp.

Que serait une conférence informatique sans "Hands On" ? Celui des http://www.xebia.com[Xébians] (Alban Phélip, Mathieu Breton et Yoann Benoit) a permis de nous familiariser avec le machine learning et le framework https://spark.apache.org/[Spark]. Il s'agissait notamment de déterminer les survivants du naufrage du Titanic en utilisant des techniques de machine learning. Nos professeurs d'un jour ont réussi à amener de la clareté sur certaines notions pourtant pas si simples de prime abord.

Sébastien Lambour de http://www.cityzendata.com/[Cityzen Data] a exposé dans sa conférence l'utilisation de la cryptographie pour vérifier la validité de requêtes sur des API. Cette validation permet de rejeter des requêtes invalides sans faire de coûteuses requêtes en base de données. La cryptographie n'est donc pas à réserver uniquement à des systèmes bancaires. En sécurisant des APIs public, on peut diminuer la charge sur notre système informatique. Cela permet ainsi de limiter l'impact de certaines attaques sur ces APIs. A méditer pour la création de vos prochaines API publiques.

Autre talk sur la sécurité, celui de Mathieu Pousse de http://zenika.com/[Zenika] qui nous a rappelé les principes et bonnes pratiques de sécurisation web et qui a conclu en nous présentant une excellente initiative : https://letsencrypt.org/[Let's Encrypt], une toute nouvelle organisation de certification automatisée, ouverte et ... gratuite (dispo en septembre 2015 - on attend ça).

Le retour d'expérience de Vladislav Pernin (http://www.erdf.fr/[ERDF]) sur la mise en place d'un broker https://kafka.apache.org/index.html[Kafka] confirme que Kafka est désormais une solution viable qu'il faut considérer notamment si votre broker de messages actuel ne parvient plus à suivre en terme de performance car sur ce point Kafka explose les scores. Alors faut-il jeter RabbitMQ à la poubelle ? Et bien la réponse est non ; comme l'a indiqué Vladislav, RabbitMQ est beaucoup plus "couteau suisse" que Kafka (fonctionnalités de de routage notamment) ; Rabbit reste donc une solution extrêmement viable si vos besoins en performances ne sont pas stratosphériques.

Pour la keynote de vendredi, il y avait de la guest star cette année : Tristan Nitot (https://cozy.io/fr/[CozyCloud]) en personne. Il est venu nous parler d'un des sujets chauds du moment : les problématiques de confidentialité sur Internet et en particulier un focus sur le projet de Loi Renseignement - très bon speaker, très bonne conférence avec des arguments qui font mouche - un nouvel exemple que le BreizhCamp a franchi un cap important : de la conférence Bretonno-Ouest des débuts, BreizhCamp est devenu une conférence d'envergure nationale et rien que pour ça, chapeau à la Team de Nicolas De Loof. Nicolas (https://www.cloudbees.com/[Cloudbees]) qui a même eu le temps de faire un talk sur les différentes voies permettant de faire évoluer votre infra sans interruption, un talk plein d'astuces et de retour d'expérience...le tout déguisé en Panda et conclu par un rap de toute beauté (la routine pour lui).

Le NoSQL n'était pas lui non plus en reste. Damien Krotkine de http://www.booking.com/[booking.com] est revenu sur la mise en place d'une base de données http://docs.basho.com/riak/latest/[Riak] pour stocker l'ensemble des évènements produits par la plateforme booking.com. Chaque heure, le site génère 100Go d'évènements différents qu'il faut stocker pour permettre leur utilisation dans des graphes, dans des outils d'aide à la prise de décision, ou encore comme source d'information pour l'A/B testing. C'est Riak qui a été choisi pour cela, car c'est l'implémentation de ring qui s'est montrée la plus robuste lors des tests (juste devant Cassandra qui était l'autre candidat shortlisté).

Bruno Bonin (http://zenika.com/[Zenika]) a quant à lui présenté les choix de modélisation qui ont été fait pour modéliser les données d'un assureur au sein d'une base documents https://www.elastic.co[Elasticsearch]. La modélisation "du bon" (préféré à celle de "la brute - document unique" et du "truand - autant de documents que de sources " !) basée sur des relations https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-parent-field.html[parent/child] a permis à Bruno d'obtenir une flexibilité dont il avait besoin pour permettre aux utilisateurs finaux d'explorer les donnnées de manière optimale.

La variété et la qualité des conférences étaient une nouvelle fois au rendez-vous et nous souhaitons donc remercier l'équipe d'organisation qui permet depuis 5 ans la tenue de cette conférence.

A l'année prochaine le Breizhcamp!